import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import {
  fetchManyInfo,
  avatarUrl,
  avatarChain,
  countryFlagEmoji,
  type CFUserInfo,
} from "@/lib/codeforces";
import { useAvatarSrc } from "@/hooks/useAvatar";
import { readRoster, SEED_HANDLES, type RosterEntry } from "@/lib/roster";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/leaderboard")({
  head: () => ({
    meta: [
      { title: "Leaderboards — Codeforces Cards" },
      {
        name: "description",
        content:
          "Rank the Codeforces cards you have generated by OVR, potential, problems solved, rating gained and contests played.",
      },
      { property: "og:title", content: "Codeforces Cards leaderboards" },
      {
        property: "og:description",
        content: "Rank your generated Codeforces Cards by OVR, potential and more.",
      },
    ],
  }),
  component: LeaderboardPage,
});

type Category = "ovr" | "rating" | "solved" | "potential" | "rising" | "contests";
type CategoryDef = (typeof CATEGORIES)[number];

/** Which pool of players to rank. */
type Source = "generated" | "featured";

const SOURCES: { key: Source; label: string }[] = [
  { key: "generated", label: "Cards generated here" },
  { key: "featured", label: "Featured players" },
];

const CATEGORIES: { key: Category; label: string; needsCard: boolean }[] = [
  { key: "ovr", label: "Highest OVR", needsCard: true },
  { key: "rating", label: "Highest rating", needsCard: false },
  { key: "solved", label: "Most solved", needsCard: true },
  { key: "potential", label: "Highest potential", needsCard: true },
  { key: "rising", label: "Fastest rising", needsCard: true },
  { key: "contests", label: "Most contests", needsCard: true },
];

interface Row {
  handle: string;
  avatar: string;
  rank: string;
  rating: number;
  country?: string | undefined;
  organization?: string | undefined;
  ovr?: number | undefined;
  potential?: number | undefined;
  solved?: number | undefined;
  contests?: number | undefined;
  gain12m?: number | undefined;
  generated: boolean;
}

/** A saved card already holds every column the table shows. */
function rosterRow(card: RosterEntry): Row {
  return {
    handle: card.handle,
    avatar: card.avatar,
    rank: card.rank,
    rating: card.rating,
    country: card.country,
    organization: card.organization,
    ovr: card.ovr,
    potential: card.potential,
    solved: card.solved,
    contests: card.contests,
    gain12m: card.gain12m,
    generated: true,
  };
}

function toRow(info: CFUserInfo, card?: RosterEntry): Row {
  return {
    handle: info.handle,
    avatar: avatarUrl(info),
    rank: info.rank ?? "unrated",
    rating: info.rating ?? 0,
    country: info.country,
    organization: info.organization,
    ovr: card?.ovr,
    potential: card?.potential,
    solved: card?.solved,
    contests: card?.contests,
    gain12m: card?.gain12m,
    generated: !!card,
  };
}

/** Same direct-then-mirror walk the cards use, in the row's smaller slot. */
function RowAvatar({ url }: { url: string }) {
  const { src, onError } = useAvatarSrc(avatarChain(url));
  if (!src) return <span className="h-10 w-10 shrink-0 rounded-lg bg-secondary" />;
  return (
    <img
      src={src}
      alt=""
      loading="lazy"
      referrerPolicy="no-referrer"
      onError={onError}
      className="h-10 w-10 shrink-0 rounded-lg object-cover"
    />
  );
}

function LeaderboardPage() {
  // Every card generated in this browser. The site is static — there is no
  // server collecting cards into one shared table — so each device keeps its
  // own board, and the copy below says so rather than implying a global one.
  const roster = useMemo(() => readRoster(), []);

  // Always opens on the generated board, empty or not: that is what the page is
  // for, and its empty state points straight at the generator.
  const [source, setSource] = useState<Source>("generated");
  const [category, setCategory] = useState<Category>("ovr");
  const [scope, setScope] = useState<"global" | "country" | "org">("global");
  const [filter, setFilter] = useState("");

  // Generated cards already carry every metric, so they rank with no network
  // call at all. Featured players are only handles, so those are fetched live.
  const featured = useQuery({
    queryKey: ["cf-bulk", SEED_HANDLES.join(",")],
    queryFn: () => fetchManyInfo(SEED_HANDLES),
    staleTime: 1000 * 60 * 15,
    retry: false,
    enabled: source === "featured",
  });

  // Ranking famous handles by OVR would mean building all their cards first —
  // three API calls each — so those categories belong to generated cards only.
  const categories = source === "generated" ? CATEGORIES : CATEGORIES.filter((c) => !c.needsCard);
  const cat = categories.find((c) => c.key === category) ?? (categories[0] as CategoryDef);

  const rows = useMemo(() => {
    let out =
      source === "generated" ? roster.map(rosterRow) : (featured.data ?? []).map((i) => toRow(i));
    const needle = filter.trim().toLowerCase();
    if (scope === "country" && needle)
      out = out.filter((r) => (r.country ?? "").toLowerCase().includes(needle));
    if (scope === "org" && needle)
      out = out.filter((r) => (r.organization ?? "").toLowerCase().includes(needle));
    const value = (r: Row) =>
      cat.key === "ovr"
        ? (r.ovr ?? 0)
        : cat.key === "rating"
          ? r.rating
          : cat.key === "solved"
            ? (r.solved ?? 0)
            : cat.key === "potential"
              ? (r.potential ?? 0)
              : cat.key === "rising"
                ? (r.gain12m ?? 0)
                : (r.contests ?? 0);
    return out.sort((a, b) => value(b) - value(a)).slice(0, 50);
  }, [source, roster, featured.data, cat.key, scope, filter]);

  // A disabled query never leaves "pending", so both flags are scoped to the
  // one source that actually fetches.
  const loading = source === "featured" && featured.isPending;
  const failed = source === "featured" && featured.error instanceof Error ? featured.error : null;

  return (
    <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6">
      <h1 className="font-display text-4xl font-bold uppercase tracking-tight sm:text-5xl">
        Leader<span className="text-gradient-gold">board</span>
      </h1>
      <p className="mt-3 text-sm text-muted-foreground">
        Ranks the cards generated in this browser. Codeforces Cards is a static site with no
        backend, so cards never leave your device and every browser keeps its own board. Switch to
        featured players for a live rating table.
      </p>

      <div className="mt-6 flex flex-wrap gap-2">
        {SOURCES.map((s) => (
          <button
            key={s.key}
            onClick={() => setSource(s.key)}
            className={cn(
              "rounded-lg border border-border/70 px-4 py-2 font-display text-xs uppercase tracking-wider transition-colors hover:border-primary",
              source === s.key && "border-primary bg-primary/15 text-primary",
            )}
          >
            {s.label}
            {s.key === "generated" && roster.length > 0 && ` (${roster.length})`}
          </button>
        ))}
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        {categories.map((c) => (
          <button
            key={c.key}
            onClick={() => setCategory(c.key)}
            className={cn(
              "rounded-full border border-border/70 px-4 py-1.5 font-display text-xs uppercase tracking-wider transition-colors hover:border-primary",
              cat.key === c.key && "border-primary bg-primary/15 text-primary",
            )}
          >
            {c.label}
          </button>
        ))}
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-2">
        {(["global", "country", "org"] as const).map((s) => (
          <button
            key={s}
            onClick={() => setScope(s)}
            className={cn(
              "rounded-lg border border-border/70 px-3 py-1.5 font-display text-xs uppercase tracking-wider transition-colors hover:border-accent",
              scope === s && "border-accent bg-accent/15 text-accent",
            )}
          >
            {s === "org" ? "College mode" : s}
          </button>
        ))}
        {scope !== "global" && (
          <Input
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder={
              scope === "country" ? "Filter by country, e.g. India" : "Filter by organization"
            }
            className="h-10 max-w-xs bg-surface/60"
          />
        )}
      </div>

      <div className="panel mt-6 overflow-hidden">
        {loading && (
          <div className="divide-y divide-border/60">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="h-16 animate-pulse bg-surface/40" />
            ))}
          </div>
        )}
        {failed && <p className="p-6 text-sm text-muted-foreground">{failed.message}</p>}
        {!loading && !failed && rows.length === 0 && (
          <div className="p-8 text-center text-sm text-muted-foreground">
            {source === "generated" ? (
              <>
                No cards generated in this browser yet —{" "}
                <Link to="/generate" className="text-primary underline-offset-4 hover:underline">
                  make the first one
                </Link>
                .
              </>
            ) : (
              "Nothing matches that filter."
            )}
          </div>
        )}
        {rows.length > 0 && (
          <ul className="divide-y divide-border/60">
            {rows.map((r, i) => (
              <li key={r.handle}>
                <Link
                  to="/player/$handle"
                  params={{ handle: r.handle }}
                  className="flex items-center gap-3 px-4 py-3 transition-colors hover:bg-secondary/50"
                >
                  <span
                    className={cn(
                      "w-8 shrink-0 font-display text-lg font-bold tabular-nums",
                      i === 0 && "text-primary",
                      i === 1 && "text-foreground",
                      i === 2 && "text-accent",
                      i > 2 && "text-muted-foreground",
                    )}
                  >
                    {i + 1}
                  </span>
                  <RowAvatar url={r.avatar} />
                  <span className="min-w-0 flex-1">
                    <span className="block truncate font-display font-bold uppercase tracking-wide">
                      {r.handle}
                    </span>
                    <span className="block truncate text-xs capitalize text-muted-foreground">
                      {r.rank}
                      {r.country ? ` · ${countryFlagEmoji(r.country)} ${r.country}` : ""}
                      {r.organization ? ` · ${r.organization}` : ""}
                    </span>
                  </span>
                  <span className="shrink-0 text-right">
                    <span className="block font-display text-lg font-bold tabular-nums text-primary">
                      {r.generated ? r.ovr : "—"}
                    </span>
                    <span className="block text-[10px] uppercase tracking-widest text-muted-foreground">
                      OVR
                    </span>
                  </span>
                  <span className="w-16 shrink-0 text-right font-display tabular-nums">
                    {r.rating || "—"}
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
